from __future__ import annotations

from .models import AIUsage, AgentProfile


PROFILES: dict[str, AgentProfile] = {
    "opc-builder": AgentProfile(
        id="opc-builder",
        name="陈默",
        role="产品与品牌顾问",
        city="杭州",
        project_summary="构建一个让独立创业者通过 Agent 找到长期合作伙伴的平台。",
        project_directions=["Agent 产品", "小团队协作", "独立创业"],
        offers=["产品策略", "产品叙事", "用户研究", "真实业务场景"],
        needs=["Agent 工程", "工作流自动化", "增长分发", "早期用户"],
        career_highlights=["8 年产品经验", "参与 3 个从 0 到 1 的 AI 产品"],
        mbti="ENTJ",
        future_goals=["完成 OPC Link MVP", "找到 20 位种子 OPC"],
        collaboration_style="异步优先，每周一次决策同步，先用两周小实验验证合作。",
        availability_hours_per_week=12,
        ai_usage=AIUsage(
            monthly_token_range="8M-15M",
            monthly_budget_cny="1000-3000",
            preferred_models=["GPT-5", "Claude"],
        ),
        direction_codes=["agent_products", "small_teams", "indie_building"],
        capability_codes=[
            "product_strategy",
            "product_narrative",
            "user_research",
            "business_scenarios",
        ],
        need_codes=[
            "agent_engineering",
            "automation",
            "growth_distribution",
            "early_users",
        ],
        value_codes=["async_first", "small_experiment", "long_term"],
        collaboration_risks=["重大产品决策需要双方共同确认"],
        open_questions=["知识产权归属", "每周实际投入时间"],
        private_contact={"email": "demo-owner@example.com", "wechat": "private-demo"},
    ),
    "shen-zhiye": AgentProfile(
        id="shen-zhiye",
        name="沈知野",
        role="独立开发者",
        city="杭州",
        project_summary="用自然语言，给小团队搭好内部工具。",
        project_directions=["Agent 产品", "小团队协作", "AI 应用开发"],
        offers=["Agent 工程", "AI 应用开发", "工作流自动化"],
        needs=["产品叙事", "早期用户", "用户研究"],
        career_highlights=["前 SaaS 技术负责人", "独立交付 12 个自动化项目"],
        mbti="INTP",
        future_goals=["服务 30 个小团队", "沉淀可复用 Agent 工作流"],
        collaboration_style="异步优先，每周可投入 12 小时；先做小实验，再决定长期合作。",
        availability_hours_per_week=12,
        ai_usage=AIUsage(
            monthly_token_range="15M-30M",
            monthly_budget_cny="2000-5000",
            preferred_models=["GPT-5", "Gemini"],
        ),
        direction_codes=["agent_products", "small_teams", "ai_apps"],
        capability_codes=["agent_engineering", "automation", "ai_app_development"],
        need_codes=["product_narrative", "early_users", "user_research"],
        value_codes=["async_first", "small_experiment", "long_term"],
        collaboration_risks=["双方都希望深度参与产品方向，需要明确最终决策机制"],
        open_questions=["产品主导权如何分配", "是否接受两周短期试合作"],
        private_contact={"phone": "13800000001", "wechat": "private-shen"},
    ),
    "lin-yu": AgentProfile(
        id="lin-yu",
        name="林予",
        role="增长顾问",
        city="上海",
        project_summary="帮 AI 产品拿到第一批海外付费用户。",
        project_directions=["AI 产品", "海外增长", "独立创业"],
        offers=["海外内容", "用户访谈", "增长实验"],
        needs=["Agent 工程", "稳定交付伙伴", "联合产品"],
        career_highlights=["前出海 SaaS 增长负责人", "帮助 6 个产品获得首批海外客户"],
        mbti="ENFP",
        future_goals=["建立海外用户研究网络", "联合孵化一款 AI 产品"],
        collaboration_style="结果导向，每周一次同步，其余时间异步推进。",
        availability_hours_per_week=10,
        ai_usage=AIUsage(
            monthly_token_range="4M-10M",
            monthly_budget_cny="500-2000",
            preferred_models=["GPT-5", "Perplexity"],
        ),
        direction_codes=["ai_products", "overseas_growth", "indie_building"],
        capability_codes=["growth_distribution", "overseas_content", "user_research"],
        need_codes=["agent_engineering", "delivery_partner", "joint_product"],
        value_codes=["async_first", "revenue_validation", "small_experiment"],
        collaboration_risks=["顾问合作与联合产品两种关系尚未选择"],
        open_questions=["合作更偏顾问还是联合产品", "目标市场优先级是否一致"],
        private_contact={"email": "private-lin@example.com", "wechat": "private-lin"},
    ),
    "zhou-yi": AgentProfile(
        id="zhou-yi",
        name="周熠",
        role="产品设计师",
        city="深圳",
        project_summary="让普通人也敢用复杂的 AI 工作流。",
        project_directions=["Agent 产品", "产品设计", "复杂工具易用化"],
        offers=["产品策略", "交互设计", "原型验证"],
        needs=["Agent 工程", "真实业务场景", "商业化验证"],
        career_highlights=["前企业软件设计负责人", "主导 4 个 AI 产品原型验证"],
        mbti="INFJ",
        future_goals=["建立 Agent 交互设计方法", "共同打磨一个真实产品"],
        collaboration_style="书面思考与高密度反馈，每周投入 8-10 小时解决一个明确问题。",
        availability_hours_per_week=9,
        ai_usage=AIUsage(
            monthly_token_range="3M-8M",
            monthly_budget_cny="500-1500",
            preferred_models=["GPT-5", "Claude"],
        ),
        direction_codes=["agent_products", "product_design", "usability"],
        capability_codes=["product_strategy", "ux_design", "prototype_validation"],
        need_codes=["agent_engineering", "business_scenarios", "monetization"],
        value_codes=["written_thinking", "small_experiment", "user_value"],
        collaboration_risks=["双方能力在产品策略上有重叠，需要划清职责边界"],
        open_questions=["真实业务场景由谁提供", "对商业化节奏的预期"],
        private_contact={"phone": "13800000003", "wechat": "private-zhou"},
    ),
}


def get_profile(agent_id: str) -> AgentProfile:
    try:
        return PROFILES[agent_id]
    except KeyError as exc:
        raise KeyError(f"Unknown OPC Agent: {agent_id}") from exc
